name: Daily Groq Content Generator

on:
  schedule:
    - cron: '0 7 * * *'  # Every day at 07:00 UTC
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Content
        run: |
          python scripts/content_bot.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/content
          git commit -m "auto: add new content from Groq bot" || echo "No changes to commit"
          git push
